<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Payroll Export</title>
    <style>
        body { font-family: Arial, sans-serif; font-size: 12px; margin: 20px; }
        h1 { color: #333; text-align: center; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th, td { border: 1px solid #000; padding: 8px; text-align: left; }
        th { background-color: #f2f2f2; }
        .total-row { font-weight: bold; background-color: #e6e6e6; }
    </style>
</head>
<body>
    <h1>Payroll Export</h1>
    <p><strong>Period:</strong> {{ $start_date }} to {{ $end_date }}</p>
    <p><strong>Company:</strong> {{ $company->name ?? 'Aeternitas' }}</p>
    <p><strong>Generated:</strong> {{ date('Y-m-d H:i:s') }}</p>
    
    <table>
        <thead>
            <tr>
                <th>Employee ID</th>
                <th>Employee Name</th>
                <th>Basic Salary</th>
                <th>Overtime</th>
                <th>Allowances</th>
                <th>Deductions</th>
                <th>Net Pay</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @foreach($payrolls as $payroll)
            <tr>
                <td>{{ $payroll->employee->employee_id ?? 'N/A' }}</td>
                <td>{{ $payroll->employee->full_name ?? 'Unknown' }}</td>
                <td>₱{{ number_format($payroll->basic_salary, 2) }}</td>
                <td>₱{{ number_format($payroll->overtime_pay ?? 0, 2) }}</td>
                <td>₱{{ number_format($payroll->allowances ?? 0, 2) }}</td>
                <td>₱{{ number_format($payroll->deductions ?? 0, 2) }}</td>
                <td>₱{{ number_format($payroll->net_pay, 2) }}</td>
                <td>{{ ucfirst($payroll->status) }}</td>
            </tr>
            @endforeach
            
            <!-- Totals Row -->
            <tr class="total-row">
                <td colspan="2">TOTALS</td>
                <td>₱{{ number_format($payrolls->sum('basic_salary'), 2) }}</td>
                <td>₱{{ number_format($payrolls->sum('overtime_pay'), 2) }}</td>
                <td>₱{{ number_format($payrolls->sum('allowances'), 2) }}</td>
                <td>₱{{ number_format($payrolls->sum('deductions'), 2) }}</td>
                <td>₱{{ number_format($payrolls->sum('net_pay'), 2) }}</td>
                <td></td>
            </tr>
        </tbody>
    </table>
    
    <div style="margin-top: 30px; font-size: 10px; color: #666;">
        <p>Total Employees: {{ $payrolls->count() }}</p>
        <p>Generated by Aeternitas Payroll System</p>
    </div>
</body>
</html>